###########
# site.url, site.title

title: 'MCSDP'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /
url: "/"


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: pretty

exclude: [ 'config.ru', 'README.md', 'vendor']


safe: true
lsi: false

